export const RECEIVE_USER = 'RECEIVE_USER';
export const RECEIVE_ADDRESS = 'RECEIVE_ADDRESS';
export const RECEIVE_USER_APPOINTMENTS = 'RECEIVE_USER_APPOINTMENTS';
export const SET_LOADER = 'SET_LOADER';
